### ISSUE TITLE
WordPress time issue after activation

### ISSUE THREAD

**Issue by bradnz** [janizde/WP-Opening-Hours#49] opened 2017-01-24 01:03 UTC
13 hours added to both GMT and local time in WordPress General Settings after plugin activation, deactivate and returns to normal. Tested on two different servers (in different countries) and 3 websites.
Version 2.0.2

**Comment by misagues** [comment] 2017-01-25 20:12
Have you tried to reverse the 2.0.2 changes manually to see if the error is there?

You can check the changes made in the commit [bfbfd80](https://github.com/janizde/WP-Opening-Hours/commit/bfbfd80d3118594559e41bec8b121b01e8a401ec)

**Comment by bradnz** [comment] 2017-01-25 20:25
No upgrade, just installed the plugin for the first time.
Not sure if I have the skills to undo the 2.0.2 changes. I'll give it ago.

**Comment by misagues** [comment] 2017-01-25 22:07
This is version 2.0.0 upload in ZippyShare http://www54.zippyshare.com/v/8j9399Od/file.html

Download and unzip the file and the folder inside (wp-opening-hours), replace in your plugin.

In the ..\wp-content\plugins

**Comment by misagues** [comment] 2017-01-25 22:13
You can also download version 2.0.1 from [here](https://github.com/janizde/WP-Opening-Hours/archive/v2.0.1.zip).

**Comment by bradnz** [comment] 2017-01-25 22:27
Disabled the plugin, copied over 2.0.0, but issue remains.

**This is before activation:**
Timezone	 Auckland
Universal time (GMT) is 2017-01-25 22:24:45. Local time is 2017-01-26 11:24:45.
This timezone is currently in daylight saving time.	
Standard time begins on: April 2, 2017 3:00 am.

**This is after:**
Timezone	 Auckland
Universal time (GMT) is 2017-01-26 11:24:58. Local time is 2017-01-27 00:24:58.
This timezone is currently in daylight saving time.	
Standard time begins on: April 2, 2017 3:00 am.

**Comment by misagues** [comment] 2017-01-26 01:14
I changed the time zone in one of the websites where I have "Open Hours" running to the Auckland area GTM + 13 and the time shows okay.

![hora_auckland_utc 13](https://cloud.githubusercontent.com/assets/16360881/22316368/07a22ee4-e36d-11e6-8f46-a7d0c335c607.JPG)


The problem has to come from something else.

**Comment by bradnz** [comment] 2017-01-26 02:46
New install of WordPress 4.7.1, no plugins installed except Opening Hours, problem remains.
PHP 7.1.0

**Activated** - Note the UTC time is 13 hours out
![image](https://cloud.githubusercontent.com/assets/25312034/22318200/9c1837c4-e3dd-11e6-80aa-884148f8e62c.png)
**Deactivated** - All normal
![image](https://cloud.githubusercontent.com/assets/25312034/22318236/d9d12cd8-e3dd-11e6-99fb-7b866b53475f.png)

**Comment by misagues** [comment] 2017-01-26 03:07
I do not know what may be happening.

Can you switch to the GTM + 1 "Madrid" time zone and then activate the Plugin?

Confirm me if that works.

**Comment by bradnz** [comment] 2017-01-26 03:18
**Deactivated** - All normal
![image](https://cloud.githubusercontent.com/assets/25312034/22318765/5632f334-e3e2-11e6-8898-6d310bf0f361.png)

**Activated** - Note UTC advanced 1 hour
![image](https://cloud.githubusercontent.com/assets/25312034/22318798/b24259da-e3e2-11e6-852c-9cfd52df4f5c.png)

**Comment by misagues** [comment] 2017-01-26 04:21
You're right, I've reviewed a website with WordPress 4.7.1 and it's not working well.

It also advances me 1 hour.

We will have to see what @janizde tells us.

**Comment by misagues** [comment] 2017-01-26 21:44
I think the problem is setting the time zone.

I've been working with the Dates.php file (classes/OpeningHours/Util/Dates.php)

` /** Sets up current timezone */
  protected function initDateTimeZone () {
    $timezoneString = get_option('timezone_string');
    $gmtOffset = get_option('gmt_offset');
    if (!empty($gmtOffset) and empty($timezoneString)) {
      $offset = floatval(floor($gmtOffset)) * 3600;
      $timezoneString = timezone_name_from_abbr(null, $offset, 0);
    }
    if (empty($timezoneString))
      $timezoneString = date_default_timezone_get();
    $this->timezone = new DateTimeZone($timezoneString);
    date_default_timezone_set($timezoneString);
  }`

But I can not find the solution. My knowledge of PHP is not very advanced either.

**Comment by gpenman** [comment] 2017-02-06 08:27
Hey there,
I'm using the plugin, and am obviously experiencing the same issue.
Any progress or solution on this?

**Comment by janizde** [comment] 2017-02-10 20:35
i will take a look asap. didn't have the time in the last couple of weeks

**Comment by gpenman** [comment] 2017-02-10 21:24
Thanks mate - i appreciate your time and effort.

**Comment by janizde** [comment] 2017-02-11 12:48
should be fixed in 2.0.3, just released it to the wp repositories. please check if it works now

**Closed by janizde** 2017-02-11 12:48 UTC

**Comment by misagues** [comment] 2017-02-14 19:50
It works perfect.
Thank you!

**Comment by bradnz** [comment] 2017-02-14 20:00
Yes, can confirm, problem fix.
Thanks.
