### ISSUE TITLE
Doesn't show subset

### ISSUE THREAD

**Issue by lorro** [janizde/WP-Opening-Hours#7] opened 2015-05-15 09:42 UTC
I have made a subset to supply different opening hours during a specific week, but it's just showing the hours of the parent set in the Opening Hours Overview widget. Could you take a look at this? 

Thanks!

**Comment by janizde** [comment] 2016-08-12 23:43
Please test it again with beta2: http://bit.ly/2bco9AZ

**Comment by janizde** [comment] 2016-10-14 12:22
@lorro please verify whether the issue is still present with beta3 otherwise I will close this one

**Closed** 2016-10-20 08:44 UTC
